services:
  fileanalysisservice:
    build:
      context: .
      dockerfile: FileAnalysisService/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./data/db:/db
      - ./data/storage:/storage
  
  
  filestorageservice:
    build:
      context: .
      dockerfile: FileStorageService/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./data/db:/db
    

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8080:8080"
